name: live_match
description: "A new Flutter project."
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.0
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get_it: ^7.7.0
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  dartz: ^0.10.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  shared_preferences: ^2.3.2
  flutter_localization: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  freezed: ^2.5.7
  json_serializable: ^6.8.0


flutter:

  uses-material-design: true

  assets:
    - assets/lang/en.json
    - assets/lang/ar.json